---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.7.2
    restart: on-failure:0
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      QNA_INFERENCE_API: 'http://qna-transformers:8080'
      NER_INFERENCE_API: 'http://ner-transformers:8080'
      SPELLCHECK_INFERENCE_API: 'http://text-spellcheck:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers,qna-transformers,ner-transformers,text-spellcheck'
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-paraphrase-mpnet-base-v2
    environment:
      ENABLE_CUDA: '0'
  qna-transformers:
    image: semitechnologies/qna-transformers:bert-large-uncased-whole-word-masking-finetuned-squad-1.0.0
    environment:
      ENABLE_CUDA: '0'
  ner-transformers:
    image: semitechnologies/ner-transformers:dbmdz-bert-large-cased-finetuned-conll03-english
    environment:
      ENABLE_CUDA: '0'
  text-spellcheck:
    image: semitechnologies/text-spellcheck-model:pyspellchecker-en
  newspublications:
    image: semitechnologies/weaviate-demo-newspublications
    environment:
    - weaviate_host=http://weaviate:4000
    depends_on:
    - weaviate
    - t2v-transformers
    - qna-transformers
    - ner-transformers
    - text-spellcheck
...
